import type { AppDefinition } from "@/types";

export const APP_REGISTRY: AppDefinition[] = [
  {
    id: "terminal",
    label: "Terminal",
    icon: "Terminal",
    defaultSize: { width: 700, height: 460 },
    minSize: { width: 400, height: 300 },
  },
  {
    id: "about",
    label: "about.brian",
    icon: "User",
    defaultSize: { width: 620, height: 500 },
    minSize: { width: 400, height: 350 },
  },
  {
    id: "axira",
    label: "AxiraNews",
    icon: "Newspaper",
    defaultSize: { width: 760, height: 560 },
    minSize: { width: 480, height: 400 },
  },
  {
    id: "projects",
    label: "Projects",
    icon: "FolderOpen",
    defaultSize: { width: 720, height: 520 },
    minSize: { width: 460, height: 360 },
  },
  {
    id: "systemmonitor",
    label: "System Monitor",
    icon: "Activity",
    defaultSize: { width: 580, height: 420 },
    minSize: { width: 400, height: 300 },
  },
  {
    id: "skills",
    label: "Skills.db",
    icon: "Database",
    defaultSize: { width: 640, height: 480 },
    minSize: { width: 420, height: 320 },
  },
  {
    id: "contact",
    label: "Contact",
    icon: "Mail",
    defaultSize: { width: 540, height: 460 },
    minSize: { width: 380, height: 360 },
  },
  {
    id: "resume",
    label: "Resume.pdf",
    icon: "FileText",
    defaultSize: { width: 660, height: 540 },
    minSize: { width: 420, height: 400 },
  },
  {
    id: "notebook",
    label: "Notebook",
    icon: "BookOpen",
    defaultSize: { width: 1100, height: 680 },
    minSize: { width: 640, height: 480 },
  },
  {
    id: "simulation",
    label: "Simulation",
    icon: "Zap",
    defaultSize: { width: 1000, height: 680 },
    minSize: { width: 640, height: 440 },
  },
  {
    id: "tor",
    label: "Tor Browser",
    icon: "Shield",
    defaultSize: { width: 900, height: 640 },
    minSize: { width: 640, height: 460 },
  },
  {
    id: "clearnet",
    label: "Clearnet Browser",
    icon: "Globe",
    defaultSize: { width: 900, height: 640 },
    minSize: { width: 600, height: 440 },
  },
  {
    id: "settings",
    label: "Settings",
    icon: "Settings",
    defaultSize: { width: 720, height: 540 },
    minSize: { width: 560, height: 400 },
  },
  {
    id: "quantum",
    label: "Quantum Lab",
    icon: "Atom",
    defaultSize: { width: 900, height: 680 },
    minSize: { width: 720, height: 520 },
  },
  {
    id: "ai",
    label: "ARIA",
    icon: "Bot",
    defaultSize: { width: 780, height: 560 },
    minSize: { width: 600, height: 420 },
  },
  {
    id: "newsroom",
    label: "Newsroom",
    icon: "PenSquare",
    defaultSize: { width: 900, height: 640 },
    minSize: { width: 700, height: 480 },
  },
  {
    id: "calculator",
    label: "Calculator",
    icon: "Calculator",
    defaultSize: { width: 320, height: 480 },
    minSize: { width: 280, height: 400 },
  },
  {
    id: "notes",
    label: "Notes",
    icon: "FileEdit",
    defaultSize: { width: 600, height: 480 },
    minSize: { width: 400, height: 320 },
  },
  {
    id: "files",
    label: "Files",
    icon: "FolderOpen",
    defaultSize: { width: 800, height: 560 },
    minSize: { width: 560, height: 400 },
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: "CalendarDays",
    defaultSize: { width: 680, height: 540 },
    minSize: { width: 500, height: 400 },
  },
  {
    id: "mediaplayer",
    label: "Media Player",
    icon: "Music2",
    defaultSize: { width: 400, height: 560 },
    minSize: { width: 360, height: 480 },
  },
  {
    id: "clipboard",
    label: "Clipboard",
    icon: "Clipboard",
    defaultSize: { width: 360, height: 520 },
    minSize: { width: 300, height: 400 },
  },
  {
    id: "compliance",
    label: "Compliance",
    icon: "Shield",
    defaultSize: { width: 780, height: 580 },
    minSize: { width: 600, height: 440 },
  },
  {
    id: "axira-showcase",
    label: "AxiraNews Showcase",
    icon: "Star",
    defaultSize: { width: 820, height: 600 },
    minSize: { width: 640, height: 480 },
  },
  {
    id: "axira-hq",
    label: "AxiraNews HQ",
    icon: "Command",
    defaultSize: { width: 900, height: 640 },
    minSize: { width: 720, height: 520 },
  },
];

export function getApp(id: string): AppDefinition | undefined {
  return APP_REGISTRY.find((a) => a.id === id);
}
